create videoComponent for catch files to backend
WildCodeSchool/2023-02-JS-Reims-project-3-origins-digital pull request #20
Opened 2023-06-06 15:29 UTC by JulienBenoit7

2023-06-06 15:41 UTC, rocambille requested changes

2023-06-06 15:41 UTC, rocambille commented on package.json
> +    "mysql": "^2.18.1"
uninstall these from root

2023-06-06 15:41 UTC, rocambille commented on frontend/src/components/VidéoComponent.jsx
> +        <div key={video.id}>
you can use a figure here

2023-06-06 15:41 UTC, rocambille commented on frontend/src/components/VidéoComponent.jsx
> +          <p>{video.title}</p>
figcaption ;)

2023-06-07 07:18 UTC, Justine-Merlin requested changes

2023-06-07 07:18 UTC, Justine-Merlin commented on frontend/src/components/VidéoComponent.jsx
No mark on letter in english, this file should be name `VideoComponent`

2023-06-07 13:12 UTC, rocambille commented on package.json
> +    "mysql": "^2.18.1"
mysql is still installed :)

2023-06-07 13:12 UTC, rocambille commented on frontend/src/components/VidéoComponent.jsx
> +        <div key={video.id}>
you used figcaption, but you forgot the figure here

2023-06-08 09:58 UTC, Justine-Merlin requested changes

2023-06-08 09:58 UTC, Justine-Merlin commented on frontend/src/images/Capture d'écran 2023-06-06 113504.png
You should rename this fil with a correct name and without whitespace.

2023-06-14 07:23 UTC, merged