S 05 all css
WildCodeSchool/2023-02-JS-Reims-project-3-origins-digital pull request #47
Opened 2023-07-05 14:06 UTC by JulienBenoit7

2023-07-05 14:15 UTC, rocambille requested changes

2023-07-05 14:15 UTC, rocambille commented on frontend/src/components/CategoryBar.css
> +  top: 0;
Don't Repeat Yourself (and Don't Contradict Yourself ;) )

2023-07-05 14:15 UTC, rocambille commented on frontend/src/components/CategoryBar.css
> +    display: flex;
Don't Repeat Yourself : what was said by default does'nt have to be said again in a media query

2023-07-05 14:15 UTC, rocambille commented on frontend/src/components/CategoryBar.css
> +@media (max-width: 768px) {
prefer mobile first : this should be min-width, not max-width

2023-07-05 14:15 UTC, rocambille commented on frontend/src/components/CategoryBar.css
> +    position: fixed;
what's wrong with sticky position ?

2023-07-05 14:15 UTC, rocambille commented on frontend/src/components/CategoryBar.css
> +    width: 93%;
no fixed with

2023-07-07 08:14 UTC, Justine-Merlin requested changes

2023-07-07 08:14 UTC, Justine-Merlin commented on frontend/src/components/CategoryBar.jsx
> +    // <nav>
Remove dead code

2023-07-07 08:24 UTC, Justine-Merlin approved these changes

2023-07-07 08:25 UTC, merged